name: hyp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  table_calendar: ^3.1.2
  intl: ^0.19.0
  google_nav_bar: ^5.0.7
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  cloud_firestore: ^5.5.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^18.0.1
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  url_launcher: ^6.2.5
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash/logo.png
  android_12:
    color: "#FFFFFF"
    image: assets/images/splash/logo.png
